require "general.options"
require "general.keymaps"
require "general.plugins"
require "general.telescope"
require "general.colorscheme"
require "general.cmp"
require "general.treesitter"
require "general.autopairs"
require "general.toggleterm"
require "general.gitsigns"
require "general.bufferline"

require "lualine-config"
require "lsp"
