require "general.options"
require "general.keymaps"
require "general.plugins"
require "general.telescope"
require "general.cmp"
require "general.treesitter"
require "general.autopairs"
require "general.toggleterm"
require "general.gitsigns"

require "theme.colorscheme"
require "theme.bufferline"
require "theme.lualine"
require "theme.alpha"

require "lsp"
